//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class hesaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hesaplar()
        {
            this.hesapharaketleri = new HashSet<hesapharaketleri>();
            this.kasaharaketleri = new HashSet<kasaharaketleri>();
            this.krediler = new HashSet<krediler>();
        }
    
        public int hesapID { get; set; }
        public int kID { get; set; }
        public int dovizID { get; set; }
        public string onayli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hesapharaketleri> hesapharaketleri { get; set; }
        public virtual parabirimi parabirimi { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kasaharaketleri> kasaharaketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<krediler> krediler { get; set; }
    }
}
