//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kasaharaketleri
    {
        public int hareketID { get; set; }
        public int krediID { get; set; }
        public int miktar { get; set; }
        public int hesapID { get; set; }
        public int islemturu { get; set; }
        public string tarih { get; set; }
        public string aciklama { get; set; }
    
        public virtual hesaplar hesaplar { get; set; }
        public virtual krediler krediler { get; set; }
    }
}
