//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class krediler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public krediler()
        {
            this.kasaharaketleri = new HashSet<kasaharaketleri>();
        }
    
        public int krediID { get; set; }
        public int hesapID { get; set; }
        public int miktar { get; set; }
        public int vade { get; set; }
        public string tarih { get; set; }
        public Nullable<int> onay { get; set; }
    
        public virtual hesaplar hesaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kasaharaketleri> kasaharaketleri { get; set; }
    }
}
