//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanicilar()
        {
            this.hesaplar = new HashSet<hesaplar>();
            this.temsilciler = new HashSet<temsilciler>();
        }
    
        public int kID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tckn { get; set; }
        public string telno { get; set; }
        public string eposta { get; set; }
        public string adres { get; set; }
        public int rolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hesaplar> hesaplar { get; set; }
        public virtual kullanicituru kullanicituru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temsilciler> temsilciler { get; set; }
    }
}
