//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class parabirimi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parabirimi()
        {
            this.hesaplar = new HashSet<hesaplar>();
        }
    
        public int dovizID { get; set; }
        public string dovizadi { get; set; }
        public Nullable<double> kur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hesaplar> hesaplar { get; set; }
    }
}
